### ISSUE TITLE
Better implement load more mechanism.

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#79] opened 2019-06-04 17:14 UTC
currently we use a workaround I thought was good enough. But judging from flatview comment numbers and the numbers reddit reports we are often missing comments. (unless the counter also shows comments even mods can't see...). 

The api has a mechanism for loadmore, time to figure out how it works.

**Comment by creesch** [comment] 2019-06-04 17:15
https://www.reddit.com/dev/api#GET_api_morechildren

**Comment by creesch** [comment] 2019-06-04 19:06
Moving to 5.1 actually... current is good enough.

**Comment by Geo1088** [comment] 2019-10-15 17:22
Duplicate of #137, fixed in f15883c for v5.2.

**Closed by Geo1088** 2019-10-15 17:22 UTC
