### ISSUE TITLE
Setting user flair from mod button dialog no longer works

### ISSUE THREAD

**Issue by dequeued0** [toolbox-team/reddit-moderator-toolbox#513] opened 2021-07-11 01:09 UTC
Starting with this release, I'm having an issue with setting user flair via the mod button dialog. I enter the new flair, hit the button to save it, and then nothing happens (the flair is not set), there's no editflair entry in the log, and I don't see an obvious error in the JavaScript console. Let me know if there's any additional information that would help.

**Comment by eritbh** [comment] 2021-07-11 02:11
Can't reproduce. Can you ensure that the request is actually never being sent, rather than being ratelimited? We're aware of some issues with the new ratelimit handler in the latest release causing various things to not work because it's following Reddit's limits more strictly than before; what's likely happening is that the request is being queued for the next time the ratelimit window resets, which could be 1-2 minutes after you click the button.

**Comment by dequeued0** [comment] 2021-07-12 03:48
Yes. I can do that. I doubt I was anywhere near the rate limit, but I'll wait it out the next time it happens. (It's working right now, but it happened multiple times before I filed the bug.)

**Comment by eritbh** [comment] 2021-07-13 04:06
Many people have been surprised at how low the ratelimit is ever since we started following the prescribed limits more strictly in 5.6.0. That behavior is mostly reverted with #514, so I'm going to link that PR as closing this issue.

**Closed** 2021-07-14 16:32 UTC
Labels: bug, core: tbapi
